#!/bin/bash

set -e

git submodule init
git submodule update
git submodule foreach git pull origin master

sudo yum update

sudo yum -y install cmake
sudo yum -y install kernel-devel gcc gcc-c++ make automake numpy
sudo yum -y install python-devel

# Dipendences for scipy
sudo yum -y install atlas-devel lapack lapack-devel blas-devel

# Installing python 2.7
if [[ -n $(python -V 2>&1 | grep 2.6) ]]; then
  sudo yum -y install python27-devel
  sudo rm /usr/bin/python
  sudo ln -s /usr/bin/python2.7 /usr/bin/python
  # Fixing yum
  sub="#!/usr/bin/python2.6"
  sudo sed "1s/.*/$sub/" $(which yum)
  # Installing pip
  sudo easy_install pip
fi

sudo pip install --upgrade numpy

mkdir junk && cd junk

set +e
pkg-config --modversion opencv
opencv_installed=$?
set -e

if [[ $opencv_installed != 0 ]]; then
  echo "Installing OpenCV..."
  if [[ ! -e "opencv-2.4.9.zip" ]]; then
    wget http://softlayer-sng.dl.sourceforge.net/project/opencvlibrary/opencv-unix/2.4.9/opencv-2.4.9.zip
  fi

  if [[ ! -e "opencv-2.4.9" ]]; then
    unzip opencv-2.4.9.zip
  fi
  cd opencv-2.4.9

  if [[ ! -d "release" ]]; then
    mkdir release
  fi

  cd release
  cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D BUILD_PYTHON_SUPPORT=ON ..
  sudo make
  sudo make install

  echo "/usr/local/lib" | sudo tee /etc/ld.so.conf.d/opencv.conf

  echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib" >> ~/.bash_profile
  echo "export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig" >> ~/.bash_profile
  echo "export PYTHONPATH=/usr/local/lib/python2.7/site-packages" >> ~/.bash_profile

  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
  export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig
else
  echo "OpenCV already installed."
fi

dropbox_folder=~/.dropbox-dist

if [[ ! -d "${dropbox_folder}" ]]; then
  echo "Installing Dropbox"
  wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf -
  wget -O dropbox.py "https://www.dropbox.com/download?dl=packages/dropbox.py"
  mv .dropbox-dist $dropbox_folder
  mv dropbox.py $dropbox_folder
fi

cd ..

rm -rf junk
echo "Starting Dropbox..."
~/.dropbox-dist >> ~/.dropbox-dist/dropbox.log 2>> ~/.dropbox-dist/dropbox.log &

echo "Please configure dropbox if you haven't did it yet..."
echo "Check ~/.dropbox-dist/dropbox.log for more details."


echo "Setting up py-video-retargeting"
cd py-video-retargeting

# Enable swapping
sudo /bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024
sudo /sbin/mkswap /var/swap.1
sudo /sbin/swapon /var/swap.1

sudo pip install -r requirements

sudo swapoff /var/swap.1
sudo rm /var/swap.1

cd ..

echo "Ready to go!"

