#!/bin/bash
bin/swapping enable
echo "Installing python 2.7 and numpy"
bin/init
echo "Check opencv existence"
bin/opencv
echo "Downloading and initilizing Dropbox"
bin/dropbox
echo "Installing libraries"
bin/requirements
bin/swapping disable
echo "Ready to go!"
exit 0
