#!/bin/bash

#DA ELIMINARE
usage() { STR=$'Usage:-p <video path>\n-s <seam>\n-f <frame>'; echo "$STR"; 1>&2; exit 1; }

s=1
f=10
p='./testing_videos/4_videos/*'
while getopts ":s:f:p:o2" arg; do
    case "${arg}" in
        p)
            p=${OPTARG}
            ;;
        s)
            s=${OPTARG}
            ((s > 0)) || usage
            ;;
        f)
            f=${OPTARG}
            ((f > 0)) || usage
            ;;
        o2) #fix a bug. has to be removed soon!
            o2=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

echo "Removing old results..."
rm -rf results/*

echo "Launching script with ${s} seam to cut and ${f} frame"
echo "python video_example.py -s ${s} -f ${f}"
python main.py -s ${s} -f ${f}

echo "Copying results to Dropbox folder"
foldername=$(date +%Y-%m-%d__%H-%M-%S)
mkdir ~/Dropbox/Tesi\ cloud/"$foldername"_result
mv -r results/* ~/Dropbox/Tesi\ cloud/"$foldername"_result
