#!/bin/bash

# Start dropbox if needed
if [[ -n $(dropbox start | grep 'following') ]]; then
  echo "error starting dropbox" && exit 1
fi

rm -rf results/*

python video_example.py

cp -r results/* ~/Dropbox/Tesi\ cloud/results
