#!/bin/bash
update() { git pull; sudo pip install --upgrade .;}

echo "Updating py-seam-merging"
cd ~/py-seam-merging
update
echo "Updating py-video-retargeting"
cd ~/py-video-retargeting
update
echo "Updating py-seam-carving"
cd ~/py-seam-carving
update
echo "Updating cloud-python-opencv"
cd ~/py-video-retargeting
git pull
